# Generated by Django 5.2.8 on 2025-11-08 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_cliente', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.habitacion'),
        ),
        migrations.AddField(
            model_name='itemservicioreserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicios_adicionales',
            field=models.ManyToManyField(through='reservas.ItemServicioReserva', to='reservas.servicio'),
        ),
        migrations.AddField(
            model_name='itemservicioreserva',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.servicio'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.tipohabitacion'),
        ),
        migrations.AlterUniqueTogether(
            name='itemservicioreserva',
            unique_together={('reserva', 'servicio')},
        ),
    ]
