# Generated by Django 5.2.8 on 2025-11-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidad_personas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
