# Generated by Django 5.2.8 on 2025-11-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_cantidad_personas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemservicioreserva',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemservicioreserva',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion_minutos',
            field=models.PositiveIntegerField(blank=True, help_text='Duración estándar del servicio en minutos', null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='personas_incluidas',
            field=models.PositiveIntegerField(default=1, help_text='Nº de personas incluidos en el precio base'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='recargo_persona_extra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Recargo por cada persona extra sobre las personas_incluidas', max_digits=10),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('SAUNA', 'Sauna'), ('MASAJE', 'Masaje'), ('TINAJA', 'Tinaja'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemservicioreserva',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemservicioreserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_servicio', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='itemservicioreserva',
            name='precio_unitario',
        ),
    ]
