# Generated by Django 5.2.8 on 2025-11-23 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_itemservicioreserva_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reservas.habitacion'),
        ),
    ]
