# Generated by Django 5.2.8 on 2025-11-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order', models.CharField(max_length=50, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('token_transbank', models.CharField(max_length=255, unique=True)),
                ('estado', models.CharField(choices=[('INICIO', 'Iniciada'), ('APROBADO', 'Aprobada'), ('RECHAZO', 'Rechazada')], default='INICIO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('codigo_autorizacion', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
