# Generated by Django 5.2.8 on 2025-11-08 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='reservas.reserva'),
        ),
    ]
